import type { Snapshot } from "../types";

/**
 * Fixture used only when the page is opened in a plain browser (no Tauri
 * bridge). It exists so the UI can be reviewed - every state at once - without
 * waiting for real sessions to happen to be in those states.
 */
export const MOCK_SNAPSHOT: Snapshot = {
  taken_at: Date.now(),
  detected: ["claude-code", "open-code", "codex", "gemini", "antigravity"],
  quota: {
    at: Date.now() - 40_000,
    source: "statusline",
    tier: "default_claude_max_5x",
    five_hour_pct: 64,
    five_hour_resets_at: new Date(Date.now() + 97 * 60_000).toISOString(),
    seven_day_pct: 34,
    seven_day_resets_at: null,
  },
  reseed: false,
  sessions: [
    {
      key: { harness: "claude-code", pid_domain: "linux:x", pid: 46597, proc_start: "1" },
      session_id: "a",
      cwd: "/home/you/code/harness-monitor",
      name: "harness-monitor",
      state: "awaiting-permission",
      state_changed_at: Date.now() - 34_000,
      started_at: Date.now() - 900_000,
      waiting_for: "permission prompt",
      model: "claude-opus-5",
      tokens: null,
      cost: null,
      is_background: false,
      tier: "full",
      jump_target: "wA:p1",
      terminal_title: "◑ harness-monitor",
    },
    {
      key: { harness: "claude-code", pid_domain: "linux:x", pid: 121148, proc_start: "2" },
      session_id: "b",
      cwd: "/home/you/code/checkout-service",
      name: "checkout-service",
      state: "awaiting-input",
      state_changed_at: Date.now() - 8_000,
      started_at: Date.now() - 3_600_000,
      waiting_for: "input needed",
      model: null,
      tokens: null,
      cost: null,
      is_background: false,
      tier: "full",
      jump_target: null,
      terminal_title: null,
    },
    {
      key: { harness: "open-code", pid_domain: "opencode:db", pid: 991, proc_start: "3" },
      session_id: "c",
      cwd: "/home/you/code/pipeline-manager",
      name: "Extract Docker spec",
      state: "running",
      state_changed_at: Date.now() - 3_000,
      started_at: Date.now() - 1_800_000,
      waiting_for: null,
      model: "omen-alpha",
      tokens: { input: 297301, output: 4210, reasoning: 1066, cache_read: 67776, cache_write: 0 },
      cost: 0.647,
      is_background: false,
      tier: "usage-only",
      jump_target: "w9:p1",
      terminal_title: "OC | Extract Docker spec",
    },
    {
      key: { harness: "open-code", pid_domain: "opencode:db", pid: 992, proc_start: "4" },
      session_id: "d",
      cwd: "/home/you/code/docs-site",
      name: "Local script, no Docker",
      state: "idle",
      state_changed_at: Date.now() - 620_000,
      started_at: Date.now() - 5_400_000,
      waiting_for: null,
      model: "omen-alpha",
      tokens: { input: 157451, output: 2210, reasoning: 0, cache_read: 12000, cache_write: 0 },
      cost: 0.272,
      is_background: false,
      tier: "usage-only",
      jump_target: "w4:p6",
      terminal_title: "OC | Local script",
    },
    {
      key: { harness: "codex", pid_domain: "codex:presence", pid: 0, proc_start: "presence" },
      session_id: "e",
      cwd: "/home/you/.codex",
      name: "codex",
      state: "active-unknown",
      state_changed_at: Date.now() - 45_000,
      started_at: Date.now() - 45_000,
      waiting_for: null,
      model: null,
      tokens: null,
      cost: null,
      is_background: false,
      tier: "presence-only",
      jump_target: null,
      terminal_title: null,
    },
  ],
};
